version: '3.8'

services:
  api:
    build:
      context: ./app
    container_name: api 
    networks:
      - toxic_comment_network

  web:
    build:
      context: ./web
    container_name: web
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - toxic_comment_network

networks:
  toxic_comment_network:
    driver: bridge